### ISSUE TITLE
CRITICAL ISSUE: Opening camera crashes app on iOS

### ISSUE THREAD

**Issue by Blasterdude** [yahelnachum/MQP_Unity_Project#36]
Pressing the camera button causes the app to crash. All other functionality seems to be intact.

Issue does not seem to appear on the android platform.

Note: may just be one device currently

**Comment by alray2569** [comment]
Can you describe what happens when the game crashes?

**Comment by alray2569** [comment]
XCode Camera permissions not set; build issue, no resolution reqd
